spring:
  application:
    name: redis-example
  data:
    redis:
      host: redis
      port: 6379
      connect-timeout: 1000
      lettuce:
        pool:
          max-idle: 8
          min-idle: 2
          max-active: 16
          max-wait: 1000